quiz_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('quizes.urls',namespace='quizes')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

quizes/urls.py
from django.urls import path
from .views import(
    QuizListView,
    quiz_view,
    quiz_data_view,
    save_quiz_view
)

app_name = 'quizes'

urlpatterns = [
    path('',QuizListView.as_view(),name='main-view'),
    path('<int:pk>/',quiz_view,name='quiz-view'),
    path('<int:pk>/data/',quiz_data_view,name='quiz_data_view'),
    path('<int:pk>/save/',save_quiz_view,name='save_quiz_view'),

]

questions/models.py
from django.db import models
from quizes.models import Quiz


# For a specific question
class Question(models.Model):
    text = models.CharField(max_length=200)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.text)

    def get_answers(self):
        return self.answer_set.all()



#To keep track of the correct answer and the option answered  by user.
class Answer(models.Model):
    text = models.CharField(max_length=200)
    correct = models.BooleanField(default=False)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"question: {self.question.text}, answer: {self.text}, correct: {self.correct}"

quizes/models.py
from django.db import models

import random

CHOICES = (
    ('easy', 'easy'),
    ('medium', 'medium'),
    ('hard', 'hard'),
)


#For defining a quiz topic
class Quiz(models.Model):
    name = models.CharField(max_length=120)
    topic = models.CharField(max_length=120)
    number = models.IntegerField()
    time = models.IntegerField(help_text="duration of the quiz in minutes")
    score_to_pass = models.IntegerField(help_text="required score in %")
    difficulty = models.CharField(max_length=6, choices=CHOICES)

    def __str__(self):
        return f"{self.name}-{self.topic}"

    def get_questions(self):
        questions = list(self.question_set.all())
        random.shuffle(questions)
        return questions[:self.number]

    class Meta:
        verbose_name_plural = 'Quizes'

results/models.py
from django.db import models
from quizes.models import Quiz
from django.contrib.auth.models import User


# For displaying the results of a quiz attempted
class Result(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    score = models.FloatField()

    def __str__(self):
        return str(self.pk)

questions/views.py
from django.shortcuts import render

# Create your views here.

quizes/views.py
from django.shortcuts import render
from .models import Quiz
from django.views.generic import ListView
from django.http import JsonResponse
from questions.models import Question, Answer
from results.models import Result

class QuizListView(ListView):
    model = Quiz
    template_name = 'quizes/main.html'


#To display list of quiz topics
def quiz_view(request, pk):
    quiz = Quiz.objects.get(pk=pk)
    return render(request, 'quizes/quiz.html',{'quiz_obj':quiz})



#To save the quiz after attempting
def save_quiz_view(request,pk):
    if request.is_ajax():
        questions = []
        data = request.POST
        data_ = dict(data.lists())
        data_.pop('csrfmiddlewaretoken')
        for key in data_.keys():
            question = Question.objects.get(text=key)
            questions.append(question)
        print(questions)

        user = request.user
        quiz = Quiz.objects.get(pk=pk)

        score = 0
        multiplier = 100 / quiz.number
        results = []
        correct_answer = None

        for q in questions:
            selected = request.POST.get(q.text)

            if selected !="":
                question_answers = Answer.objects.filter(question=q)
                for a in question_answers:
                    if selected == a.text:
                        if a.correct:
                            score +=1
                            correct_answer = a.text
                    else:
                        if a.correct:
                            correct_answer = a.text

                results.append({str(q): {'correct_answer':correct_answer,'answered':selected}})   
            else:
                results.append({str(q): 'not answered'})

        score_ = score*multiplier 
        Result.objects.create(quiz=quiz, user=user, score=score_)

        if score_ >= quiz.score_to_pass:
            return JsonResponse({'passed':True, 'score':score_, 'results':results})

        else:
            return JsonResponse({'passed':False, 'score':score_, 'results':results})



#To display the quiz questions
def quiz_data_view(request, pk):
    quiz = Quiz.objects.get(pk=pk)
    questions = []
    for ques in quiz.get_questions():
        ans=[]
        for a in ques.get_answers():
            ans.append(a.text)
        questions.append({str(ques):ans})
    return JsonResponse({
        'data':questions,
        'time':quiz.time,
    })

results/views.py
from django.shortcuts import render

# Create your views here.

quizes/templates/quizes/main.html
{% extends "base.html" %}
{% load static %}

{% block scripts %}
    <script src="{% static 'quizes/main.js' %}" defer></script>
{% endblock scripts %}

{% block title %}
home
{% endblock title %}

{% block content %}
<!-- Modal -->
  <div class="modal fade" id="quizStartModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Start</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body" id="modal-body-confirm">
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
          <button type="button" id="start-button" class="btn btn-primary">Yes</button>
        </div>
      </div>
    </div>
  </div>

<div >
    <h1 style="text-align: center; font-family: Georgia, 'Times New Roman', Times, serif;">Quizzz Time!!!</h1>
</div>
<hr>
<p style="text-align: center; font-family: Georgia, 'Times New Roman', Times, serif;">Welcome to the Quiz-a-thon! </p>
<p style="text-align: center; font-family: Georgia, 'Times New Roman', Times, serif;">Rules are simple :) You'll have to chose one among the below topics and attempt the given questions within the specified time limit. </p>
<p style="text-align: center; font-size: larger;"><i >All The Best!</i></p>
<br>
<br>
{% for obj in object_list %}
<div class='row text-center' style="border: 2px;">
  <div class='col-8 col-md-6 mx-auto border rounded py-3 mb-4' style="background-color: rgb(194, 187, 187);">
    <button class="btn btn-link modal-button" data-pk="{{obj.pk}}" data-quiz="{{obj.name}}" data-questions="{{obj.number}}" data-difficulty="{{obj.difficulty}}" data-time="{{obj.time}}" 
    data-pass="{{obj.score_to_pass}}"  data-toggle="modal" data-target="#quizStartModal" style="font-size: larger; color: black;">{{obj.name}}</button>
    <br>
    <p>This is a quiz based on basic knowledge of {{obj.topic}}.</p>
  </div>
</div>
{% endfor %}
{% endblock content %}

quizes/templates/quizes/quiz.html
{% extends "base.html" %}
{% load static %}

{% block scripts %}
    <script src="{% static 'quizes/quiz.js' %}" defer></script>
{% endblock scripts %}


{% block title %}
{{quiz_obj.name}}
{% endblock title %}

{% block content %}

<div class="row">
    <div class="col"><a href="{% url 'quizes:main-view' %}" class="btn btn-primary">Go Back</a></div>
    <div class="col text-right" id="timer-box"></div>
</div>
<div class="row">
        <div class="col justify-content-center">
            <p style="text-align: center; font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif; font-size: larger; font-weight: bold; text-transform: uppercase;">{{quiz_obj.name}}</p>
            <p style="text-align: center;">Score to Pass: {{quiz_obj.score_to_pass}}%</p>
        </div>
</div>




<form id="quiz-form" class="mt-3 mb-3">
    {% csrf_token %}
    <div class="flex-container" style="display: flex;justify-content: space-around;">
        <div class="card w-75 ">
            <div class="card-body card-border-color=black" >
                <p class="card-text"><div id="quiz-box"></div></p>
            </div>
        </div>
    </div>
    <br>
    <br>
    <button type="submit" class="btn btn-primary mt-3" style="float:center ;justify-content: center; align-items: center; margin-left: 45%; width:4cm">Save</button>
</form>




<div id="result-box">
</div>
<br>
<div id="score-box" style="text-align: center;">
</div>

{% endblock content %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- favicon -->
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- jquery -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

    <!-- custom css & js-->
    <link rel="stylesheet" href={% static 'style.css' %}>

    {% block scripts %}
    {% endblock scripts %}

    <title>quiz app| {% block title %}{% endblock title %}</title>
  </head>
  <body>
    <div class="container mt-3">
        {% block content %}
        {% endblock content %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
  </body>
</html>